# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.IntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip', models.CharField(max_length=16, unique=True)),
                ('status', models.IntegerField()),
                ('size', models.FloatField(default=8589.93)),
                ('cost', models.FloatField(default=429.49)),
            ],
        ),
    ]
