# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiramisu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requirements',
            fields=[
                ('vm_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latency', models.IntegerField()),
                ('latency_max', models.IntegerField()),
                ('percentl', models.IntegerField()),
                ('iops_min', models.IntegerField()),
                ('iops', models.IntegerField()),
                ('percenti', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('cost_max', models.IntegerField()),
                ('percentc', models.IntegerField()),
                ('app_type', models.IntegerField()),
            ],
        ),
    ]
