# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiramisu', '0002_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='storage',
            fields=[
                ('vm_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('current_pool', models.CharField(max_length=10)),
                ('appropiate_pool', models.CharField(max_length=10)),
            ],
        ),
    ]
