# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiramisu', '0003_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('vm_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latency_min', models.IntegerField()),
                ('latency', models.IntegerField()),
                ('latency_max', models.IntegerField()),
                ('percentl', models.IntegerField()),
                ('iops_min', models.IntegerField()),
                ('iops', models.IntegerField()),
                ('iops_max', models.IntegerField()),
                ('percenti', models.IntegerField()),
                ('cost_min', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('cost_max', models.IntegerField()),
                ('percentc', models.IntegerField()),
                ('app_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('vm_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latency', models.IntegerField()),
                ('iops', models.IntegerField()),
                ('latency_hdd', models.IntegerField()),
                ('iops_hdd', models.IntegerField()),
                ('latency_ssd', models.IntegerField()),
                ('iops_ssd', models.IntegerField()),
            ],
        ),
    ]
