# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiramisu', '0004_cube_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='owner',
            field=models.IntegerField(default=0),
        ),
    ]
