# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiramisu', '0006_auto_20160209_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='notice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cube',
            name='app_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='app_type',
            field=models.IntegerField(),
        ),
    ]
