# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiramisu', '0006_auto_20160209_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='name_display',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='cube',
            name='app_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='app_type',
            field=models.IntegerField(),
        ),
    ]
