# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiramisu', '0007_auto_20160209_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='notice',
            field=models.IntegerField(default=1),
        ),
    ]
